package com.mycompany.mecatech.views;

import com.mycompany.mecatech.DAOclientesImpl;
import com.mycompany.mecatech.interfaces.DAOclientes;
import java.awt.Color;


public class ViewNewCliente extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.mecatech.models.clientes clienteEdition;

    public ViewNewCliente() {
        initComponents();
        InitStyles();
    }

    public ViewNewCliente(com.mycompany.mecatech.models.clientes cliente) {
        initComponents();
        isEdition = true;
        clienteEdition = cliente;
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h2");
        title.setForeground(Color.black);
        nomCliente.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del Cliente");
        nomEncargado.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del encargado.");
        telefonoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el telefono.");
        correoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el correo.");

        if (isEdition) {
            title.setText("Editar Cliente");
            button.setText("Guardar");
            
            if (clienteEdition != null) {
                nomCliente.setText(clienteEdition.getNom_cliente());
                nomEncargado.setText(clienteEdition.getEncargado());
                telefonoTxt.setText(clienteEdition.getTelefono());
                correoTxt.setText(clienteEdition.getCorreo());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        nomCliente = new javax.swing.JTextField();
        Encargado = new javax.swing.JLabel();
        nomEncargado = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Registrar Cliente Nuevo");

        Cliente.setText("Cliente");

        nomCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomClienteKeyTyped(evt);
            }
        });

        Encargado.setText("Encargado");

        nomEncargado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomEncargadoKeyTyped(evt);
            }
        });

        Telefono.setText("Telefono");

        telefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTxtKeyTyped(evt);
            }
        });

        Correo.setText("Correo");

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Registrar");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Encargado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(correoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(telefonoTxt)
                            .addComponent(nomEncargado)
                            .addComponent(nomCliente))
                        .addGap(244, 244, 244))))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(8, 8, 8)
                .addComponent(Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Encargado, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
       String nCliente = nomCliente.getText();
       String nEncargado = nomEncargado.getText();
       String telf = telefonoTxt.getText();
       String mail = correoTxt.getText();
       
       // Validaciones para los campos
       if (nCliente.isEmpty()|| nEncargado.isEmpty() || telf.isEmpty() || mail.isEmpty() ){
          javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
          nomCliente.requestFocus();
          return;
       } 
       // Validacion de numero telefonico
        if (telefonoTxt.getText().length()!=9) {
            javax.swing.JOptionPane.showMessageDialog(this, "Numero incorrecto, debe ingresar 9 digitos.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        } 
       //validacion de correo
       if(!correoTxt.getText().contains("@")||!correoTxt.getText().contains(".")){
           javax.swing.JOptionPane.showMessageDialog(this, "Correo no valido.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
       }
       com.mycompany.mecatech.models.clientes cliente = isEdition ? clienteEdition : new com.mycompany.mecatech.models.clientes();
       cliente.setNom_cliente(nCliente);
       cliente.setEncargado(nEncargado);
       cliente.setTelefono(telf);
       cliente.setCorreo(mail);
       
        try {
            DAOclientes dao = new DAOclientesImpl();
            
            if (!isEdition) {
                dao.registrar(cliente);
            }else{
                dao.modificar(cliente);
            }
            
            String successMsg = isEdition ? "modificado" : "registrado";
            javax.swing.JOptionPane.showMessageDialog(this,"Cliente " + successMsg + " exitosamente. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE );
            if (!isEdition) {
               nomCliente.setText("");
               nomEncargado.setText("");
               telefonoTxt.setText("");
               correoTxt.setText("");
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el cliente.  \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void telefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTxtKeyTyped
        char c = evt.getKeyChar();
        if (c>='0'&& c<='9'&& telefonoTxt.getText().length()<9) {
            
        }else{
            evt.consume();
        }
        if (telefonoTxt.getText().length()==0 && c!='9') {
            evt.consume();
        }
    }//GEN-LAST:event_telefonoTxtKeyTyped

    private void nomClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomClienteKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'||c>'z')&&(c<'A'||c>'Z'))evt.consume();
    }//GEN-LAST:event_nomClienteKeyTyped

    private void nomEncargadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomEncargadoKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'||c>'z')&&(c<'A'||c>'Z'))evt.consume();
    }//GEN-LAST:event_nomEncargadoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cliente;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Encargado;
    private javax.swing.JLabel Telefono;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JTextField nomCliente;
    private javax.swing.JTextField nomEncargado;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}