package com.mycompany.mecatech.views;


import com.mycompany.mecatech.DAOequiposImpl;
import com.mycompany.mecatech.DAOordentrabajoImpl;
import com.mycompany.mecatech.interfaces.DAOequipos;
import com.mycompany.mecatech.interfaces.DAOordenTrabajos;
import com.mycompany.mecatech.utils.Utils;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ViewNewOrdenTrabajo extends javax.swing.JPanel {
    boolean isEdition = false;
    com.mycompany.mecatech.models.OrdenTrabajos oitEdition;
   
    public ViewNewOrdenTrabajo() {
        initComponents();
        InitStyles();
    }
    public ViewNewOrdenTrabajo(com.mycompany.mecatech.models.OrdenTrabajos oit) {
        initComponents();
        isEdition = true;
        oitEdition = oit;
        InitStyles();
    }
    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h2");
        title.setForeground(Color.black);
        oitTxt.putClientProperty("JTextField.placeholderText", "Asignar codigo");
        idEquipoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el codigo del equipo.");
        descripcionTxt.putClientProperty("JTextField.placeholderText", "Ingrese descripcion del trabajo.");
        fechaEntrgTxt.putClientProperty("JTextField.placeholderText", "Asigna fecha de entrega.");
        
        if (isEdition) {
            title.setText("Editar Orden de Trabajo");
            button.setText("Guardar");
            
            if (oitEdition != null) {
                oitTxt.setText(oitEdition.getOIT());
                idEquipoTxt.setText(oitEdition.getID_equipo()+"");
                descripcionTxt.setText(oitEdition.getDescripcion());
                fechaEntrgTxt.setText(oitEdition.getFechaEntrega()+"");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        oit = new javax.swing.JLabel();
        oitTxt = new javax.swing.JTextField();
        idEquipo = new javax.swing.JLabel();
        idEquipoTxt = new javax.swing.JTextField();
        Descripción = new javax.swing.JLabel();
        descripcionTxt = new javax.swing.JTextField();
        FechaEntrega = new javax.swing.JLabel();
        fechaEntrgTxt = new javax.swing.JTextField();
        button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Crear Orden de Trabajo");

        oit.setText("OIT");

        idEquipo.setText("ID Equipo");

        Descripción.setText("Descripción");

        FechaEntrega.setText("Fecha de Entrega");

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Crear");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Descripción, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descripcionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(idEquipoTxt)
                    .addComponent(oitTxt)
                    .addComponent(FechaEntrega, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaEntrgTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addGap(244, 244, 244))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oit, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idEquipoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripción, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaEntrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        try {
            String OITs = oitTxt.getText();
            String idEqp = idEquipoTxt.getText();
            String dscrp = descripcionTxt.getText();
            String fEntrg = fechaEntrgTxt.getText();
            
            // Validaciones para los campos
            if (OITs.isEmpty()||idEqp.isEmpty()||dscrp.isEmpty()||fEntrg.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                oitTxt.requestFocus();
                return;
            }else if (!Utils.isNumeric(idEqp)) {
                javax.swing.JOptionPane.showMessageDialog(this,"El campo ID Equipo debe ser un numero entero");
                idEquipoTxt.requestFocus();
                return;
            }else if (Integer.parseInt(idEqp)<=0){
                javax.swing.JOptionPane.showMessageDialog(this, "El campo ID Equipo debe ser mayor que 0. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
            DAOequipos daoEquipos = new DAOequiposImpl();
            
            com.mycompany.mecatech.models.equipos currentEquipo = daoEquipos.getEquiposID(Integer.parseInt(idEqp));
            if (currentEquipo == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún equipo con ese ID. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                idEquipoTxt.requestFocus();
                return;
            }
            
            com.mycompany.mecatech.models.OrdenTrabajos oit = isEdition ? oitEdition : new  com.mycompany.mecatech.models.OrdenTrabajos();
            oit.setOIT(OITs);
            oit.setID_equipo(Integer.parseInt(idEqp));
            oit.setDescripcion(dscrp);
            oit.setFechaEntrega((fEntrg));
            
            try {
                DAOordenTrabajos dao = new DAOordentrabajoImpl();
                
                if (!isEdition) {
                    dao.registrar(oit);
                }else{
                    dao.modificar(oit);
                }
                
                String successMsg = isEdition ? "modificado" : "registrado";
                
                javax.swing.JOptionPane.showMessageDialog(this,"OIT " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE );
                
                if (!isEdition) {
                    oitTxt.setText("");
                    idEquipoTxt.setText("");
                    descripcionTxt.setText("");
                    fechaEntrgTxt.setText("");
                }
            } catch (Exception e) {
                String errorMsg = isEdition ? "modficar" : "registrar";
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " la OIT. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewNewOrdenTrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripción;
    private javax.swing.JLabel FechaEntrega;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JTextField descripcionTxt;
    private javax.swing.JTextField fechaEntrgTxt;
    private javax.swing.JLabel idEquipo;
    private javax.swing.JTextField idEquipoTxt;
    private javax.swing.JLabel oit;
    private javax.swing.JTextField oitTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}