/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mecatech;

import com.mycompany.mecatech.views.clientes;
import com.mycompany.mecatech.views.principal;
import com.mycompany.mecatech.views.HistorialMantenimiento;
import com.mycompany.mecatech.views.equipos;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author Aldair Raymundo
 */
public class Dashborad extends javax.swing.JFrame {

    /**
     * Creates new form Dashborad
     */
        public Dashborad() {
            initComponents();
            initStyles();
            SetDate();
            initContent();
        }

    /**
     *
     */
        public final void initStyles(){
            navText.putClientProperty( "FlatLaf.style", "font: 16 $light.font" );
            navText.setForeground(Color.white);
            mensaje.putClientProperty( "FlatLaf.style", "font: bold $h2.regular.font" );
            mensaje.setForeground(Color.black);
            dateText.putClientProperty( "FlatLaf.style", "font: 24 $light.font" );
            dateText.setForeground(Color.white);
        }
     
        private void SetDate() {
            LocalDate now = LocalDate.now();
            Locale spanishLocale = new Locale("es", "ES");
            dateText.setText(now.format(DateTimeFormatter.ofPattern("EEEE dd 'de' MMMM 'del' yyyy", spanishLocale)));
        }
        
        private void initContent(){
            ShowJPanel(new principal());
        }
        
        public static void ShowJPanel(JPanel p) {
            p.setSize(750,450);
            p.setLocation(0,0);
            
            content.removeAll();
            content.add(p, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        principalButton = new javax.swing.JButton();
        equiposButton = new javax.swing.JButton();
        clientesButton = new javax.swing.JButton();
        hMantenimientoButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        dateText = new javax.swing.JLabel();
        navText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 650));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1020, 650));

        menu.setBackground(new java.awt.Color(13, 71, 161));
        menu.setPreferredSize(new java.awt.Dimension(270, 650));

        logo.setBackground(new java.awt.Color(0, 0, 0));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecatech.png"))); // NOI18N

        principalButton.setBackground(new java.awt.Color(25, 118, 210));
        principalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        principalButton.setForeground(new java.awt.Color(255, 255, 255));
        principalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal_icono.png"))); // NOI18N
        principalButton.setText("Principal");
        principalButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        principalButton.setBorderPainted(false);
        principalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principalButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        principalButton.setIconTextGap(15);
        principalButton.setPreferredSize(new java.awt.Dimension(270, 40));
        principalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalButtonActionPerformed(evt);
            }
        });

        equiposButton.setBackground(new java.awt.Color(25, 118, 210));
        equiposButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        equiposButton.setForeground(new java.awt.Color(255, 255, 255));
        equiposButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equipos_icono.png"))); // NOI18N
        equiposButton.setText("Equipos");
        equiposButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        equiposButton.setBorderPainted(false);
        equiposButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equiposButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        equiposButton.setIconTextGap(15);
        equiposButton.setPreferredSize(new java.awt.Dimension(270, 40));
        equiposButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiposButtonActionPerformed(evt);
            }
        });

        clientesButton.setBackground(new java.awt.Color(25, 118, 210));
        clientesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clientesButton.setForeground(new java.awt.Color(255, 255, 255));
        clientesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes_icono.png"))); // NOI18N
        clientesButton.setText("Clientes");
        clientesButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        clientesButton.setBorderPainted(false);
        clientesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientesButton.setIconTextGap(15);
        clientesButton.setPreferredSize(new java.awt.Dimension(270, 40));
        clientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesButtonActionPerformed(evt);
            }
        });

        hMantenimientoButton.setBackground(new java.awt.Color(25, 118, 210));
        hMantenimientoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hMantenimientoButton.setForeground(new java.awt.Color(255, 255, 255));
        hMantenimientoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regsMant_icono.png"))); // NOI18N
        hMantenimientoButton.setText("Historial de mantenimiento");
        hMantenimientoButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        hMantenimientoButton.setBorderPainted(false);
        hMantenimientoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hMantenimientoButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hMantenimientoButton.setIconTextGap(15);
        hMantenimientoButton.setPreferredSize(new java.awt.Dimension(270, 40));
        hMantenimientoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hMantenimientoButtonActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(25, 118, 210));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informes_icono.png"))); // NOI18N
        jButton5.setText("Informes");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(15);
        jButton5.setPreferredSize(new java.awt.Dimension(270, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo))
            .addComponent(principalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(equiposButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clientesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hMantenimientoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo)
                .addGap(30, 30, 30)
                .addComponent(principalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(equiposButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(clientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(hMantenimientoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(25, 118, 210));
        header.setPreferredSize(new java.awt.Dimension(750, 150));

        dateText.setText("{dayname} {day} de {moth} del {year}  ");
        dateText.setPreferredSize(new java.awt.Dimension(240, 20));

        navText.setText("Que tenemos para hoy {name} ?");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(navText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addGap(347, 347, 347))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(navText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(750, 450));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mensaje.setText("        Sistema de diagnóstico y mantenimiento de Equipos de Bombeo Industriales");
        mensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mensaje.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void equiposButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiposButtonActionPerformed
        ShowJPanel(new equipos());
    }//GEN-LAST:event_equiposButtonActionPerformed

    private void principalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalButtonActionPerformed
        ShowJPanel(new principal());
    }//GEN-LAST:event_principalButtonActionPerformed

    private void clientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesButtonActionPerformed
        ShowJPanel(new clientes());
    }//GEN-LAST:event_clientesButtonActionPerformed

    private void hMantenimientoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hMantenimientoButtonActionPerformed
        ShowJPanel(new HistorialMantenimiento());
    }//GEN-LAST:event_hMantenimientoButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashborad().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton clientesButton;
    private static javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton equiposButton;
    private javax.swing.JButton hMantenimientoButton;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel navText;
    private javax.swing.JButton principalButton;
    // End of variables declaration//GEN-END:variables
}
